### ISSUE TITLE
No changes under Thermostat > State

### ISSUE THREAD

**Issue by MSL-DA** [ussaka/Danfoss-Ally-HA-automations#4]
Thanks for your work 👍

Unfortunately I have to admit that I can't get it to work. If I check in zigbee2mqtt and state under each thermostat, there are no changes.

I don't get any error messages in HA

Is there anything I can do to troubleshoot?

I would just like to add that I am using [Danfoss Ally Room Load Balancing](https://community.home-assistant.io/t/zigbee2mqtt-danfoss-ally-trv-room-load-balancing/468526) and [Danfoss Ally Ext Temp Z2M v2](https://community.home-assistant.io/t/zigbee2mqtt-danfoss-ally-send-external-temperature-to-trv-version-2/627564) without any problems

Edit: I am not using zigbee2mqtt addon in HA

```
{
    "adaptation_run_control": "none",
    "adaptation_run_settings": true,
    "adaptation_run_status": "found",
    "algorithm_scale_factor": 1,
    "battery": 85,
    "day_of_week": "thursday",
    "external_measured_room_sensor": 2130,
    "heat_available": true,
    "heat_required": true,
    "keypad_lockout": "unlock",
    "linkquality": 152,
    "load_balancing_enable": true,
    "load_estimate": 447,
    "load_room_mean": 476,
    "local_temperature": 21.4,
    "mounted_mode_active": false,
    "mounted_mode_control": false,
    "occupied_heating_setpoint": 21,
    "occupied_heating_setpoint_scheduled": 21,
    "pi_heating_demand": 20,
    "preheat_status": false,
    "programming_operation_mode": "setpoint",
    "radiator_covered": false,
    "regulation_setpoint_offset": 0,
    "running_state": "heat",
    "setpoint_change_source": "schedule",
    "system_mode": "heat",
    "thermostat_vertical_orientation": false,
    "trigger_time": 660,
    "update": {
        "installed_version": 28,
        "latest_version": 28,
        "state": "idle"
    },
    "viewing_direction": false,
    "window_open_external": false,
    "window_open_feature": false,
    "window_open_internal": "closed",
    "update_available": null
}
```

**Comment by ussaka** [comment]
Hi,

Your `setpoint_change_source` shows `schedule` which would indicate that your _Weekly schedule script_ is working. I have found that best place to verify it is HA settings --> Devices --> MQTT --> Danfoss Ally --> Occupied heating setpoint. Which show the time for when setpoint has changed.

![image](https://github.com/user-attachments/assets/14654088-d059-43d8-b86e-afed9ab1ad32)

To verify you have correct time you can use z2m Dev console (after clicking the device) with cluster=`genTime `and attribute=`time`. Which will return epoch, keep in mind this is not normal epoch but since 1.1.2000.

![image](https://github.com/user-attachments/assets/b99394b7-48fa-49d9-b4c6-7fc7827d3f77)

Let me know if you still can't get it to work. I have used only one Danfoss Ally. I will getting a second one and improving the schedule script in this winter.

**Comment by MSL-DA** [comment]
Thanks for the quick reply :)

Unfortunately the time is not being written to Z2M (1.41.0-dev commit: 5ca4cf4)

<img width="1027" alt="Skærmbillede 2024-11-27 kl  14 13 44" src="https://github.com/user-attachments/assets/7a19971b-5738-48c0-a269-725a1def0d02">

<img width="558" alt="Skærmbillede 2024-11-27 kl  14 12 35" src="https://github.com/user-attachments/assets/e3dba755-65d4-43c1-8578-6a0b7038103f">

<img width="558" alt="Skærmbillede 2024-11-27 kl  14 13 01" src="https://github.com/user-attachments/assets/24b7c53f-31f0-4b42-9429-b65f6ee37a2b">

<img width="558" alt="Skærmbillede 2024-11-27 kl  14 13 09" src="https://github.com/user-attachments/assets/866c54af-8a3a-4844-864e-0234eac68271">

<img width="1825" alt="Skærmbillede 2024-11-27 kl  14 38 38" src="https://github.com/user-attachments/assets/c7e99963-aeef-4adb-9c91-41587a109857">

**Comment by ussaka** [comment]
Also check what `Weekly schedule`(bitmap) you use on schedule. You should try with `127` which will set the schedule to work every day. It's bit misleading that one must use dec instead of hex with the script at the moment.

**Comment by MSL-DA** [comment]
I am getting this error

<img width="1232" alt="Skærmbillede 2024-11-29 kl  17 04 09" src="https://github.com/user-attachments/assets/e85e5017-4cca-49cf-9b62-1b7ff39bbe92">

**Comment by MSL-DA** [comment]
But I think I misunderstood the whole point of this topic.

I had Ally's Gateway previously. When I wanted 21 degrees at 7am, Ally calculated when and how much the thermostats should open. I assumed it was calculated from a learning curve.

When I look at your schedule, I can see that you have 6 set points where the temperature and time increase gradually.

I have tried this with 127 in `Weekdays to run the schedule`

but I still get the above error

**Comment by ussaka** [comment]
> I am getting this error
> <img alt="Skærmbillede 2024-11-29 kl 17 04 09" width="1232" src="https://private-user-images.githubusercontent.com/134940586/391165770-e85e5017-4cca-49cf-9b62-1b7ff39bbe92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwNzk5MDEsIm5iZiI6MTczMzA3OTYwMSwicGF0aCI6Ii8xMzQ5NDA1ODYvMzkxMTY1NzcwLWU4NWU1MDE3LTRjY2EtNDljZi05YjYyLTFiN2ZmMzliYmU5Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwMVQxOTAwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMjE2Y2ZkZjFiODFmMWNlZDcwMjc1OWEwYjEyMzdkZGQ4NGZjNTJjYTdlODU5OWMxMmJlMDE5OWQ5M2E0ZGFmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5TFmCR4pVnpC1XcArKtrRoB4C9UuN8-ZohnYvkcSXaQ">

It says you are missing a parameter. Double check you use `{"daystoreturn":1,"modetoreturn":1}` payload. I can reproduce your log message if I misspell `daystoreturn`.  


> I had Ally's Gateway previously. When I wanted 21 degrees at 7am, Ally calculated when and how much the thermostats should open. I assumed it was calculated from a learning curve.

I'm not sure does the Gateway actually work as you describe. I think it would work same way as my script. Anyway my script changes the Ally's target temperature value at the given time. After the target has changed it tries to reach it. I want my target to change multiple times so I have a few different temperatures on the transitions.

**Comment by MSL-DA** [comment]
Thanks for the help 👍

I got it working. It would be really great if you could implement `PreHeatCommand` 😊

**Comment by MSL-DA** [comment]
> I'm not sure do you need to run same schedule on all of the Allys that are connected to same room load balancing.

I don't have a scheduler on these thermostats yet, but if I'm reading correctly, it's not necessary.

I'll wait a bit on those thermostats until I know how long my radiators will take to heat my rooms and if Load balancing is working as intended.

**Comment by MSL-DA** [comment]
What is the correct way to edit the schedule?

If I enter 0x0201 and 0x03, the current schedule is not deleted.

**Comment by MSL-DA** [comment]
Can you tell me what I need to do to make it work from Sunday 9.30pm to Friday 7am and from Friday 11pm to Sunday 8am?

**Comment by ussaka** [comment]
You need to set two schedules. Use Window calculator in programmer mode to get the mask for the weekdays.

![image](https://github.com/user-attachments/assets/8e3fbfc9-2897-4492-ae86-1407bf0943e7)

I don't remember what day was bit 0 but above shows schedule set for all weekdays. So e.g. if bit 0 is Sunday and you don't want the schedule to run on Sundays click first `1` to `0` and you get 126 that you need to input to the script.

I'm traveling atm. I'll respond to your remaining questions in early January.

**Comment by MSL-DA** [comment]
> You need to set two schedules. Use Window calculator in programmer mode to get the mask for the weekdays.
> 
> ![image](https://private-user-images.githubusercontent.com/72491928/396355352-8e3fbfc9-2897-4492-ae86-1407bf0943e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NjU0NjQsIm5iZiI6MTczNDQ2NTE2NCwicGF0aCI6Ii83MjQ5MTkyOC8zOTYzNTUzNTItOGUzZmJmYzktMjg5Ny00NDkyLWFlODYtMTQwN2JmMDk0M2U3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE3VDE5NTI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NDg0YjU0Nzg2OWJjN2JjNjM0YmVmMzExN2MxMzkzYjk3YmFmY2RiYTI1NDY2YjkyZDMwZTcwYjAxYzZhYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xgtuUS5cjQZkBqo6XulzTBp-tpcKq2stBI3tdZOUIRI)
> 
> I don't remember what day was bit 0 but above shows schedule set for all weekdays. So e.g. if bit 0 is Sunday and you don't want the schedule to run on Sundays click first `1` to `0` and you get 126 that you need to input to the script.
> 
> I'm traveling atm. I'll respond to your remaining questions in early January.

Thanks ... I used chatgpt to convert monday to friday to bitmap 🫢

Merry Christmas to you
